_target_: flower_vla.trainers.flower_trainer.AccelerateTrainer
_recursive_: false

defaults:
  - agent: meanflower_vla

use_torch_compile: False
single_optimizer: False
learning_rate_dit: 1e-4
learning_rate_vlm: 1e-5
use_lr_scheduler: True
beta_dit_1: 0.9
beta_dit_2: 0.95
beta_vlm_1: 0.9
beta_vlm_2: 0.99
weight_decay:
  transformer_weight_decay: 0.01
  vlm_weight_decay: 0.001
  decoder_weight_decay: 0.05

early_stopping_patience: 5

dit_lr_scheduler:
  _target_: flower_vla.utils.lr_schedulers.TriStageLRScheduler
  total_steps: 100000
  phase_ratio: "(0.03, 0.17, 0.8)"
  init_lr_scale: 0.01
  final_lr_scale: 0.01

vlm_lr_scheduler:
  _target_: flower_vla.utils.lr_schedulers.TriStageLRScheduler
  init_lr_scale: 0.001
  final_lr_scale: 0.5
  phase_ratio: "(0.05, 0.15, 0.8)"
  total_steps: 100000

eval_every_n_steps: ${eval_every_n_steps}
save_every_n_steps: ${save_every_n_steps} 
max_train_steps: ${max_train_steps}
max_eval_steps: ${max_eval_steps}

use_ema: True
decay: ${decay}
rampup_ratio: ${rampup_ratio}
update_ema_every_n_steps: ${update_ema_every_n_steps}
batch_size: ${batch_size}

obs_modalities: ${obs_modalities}
goal_modalities: ${goal_modalities}
img_modalities: ${img_modalities} 
lang_modalities: ${lang_modalities}
target_modality: ${target_modality}