_target_: flower_vla.dataset.datamodule.UhaDataModule 
_recursive_: false
defaults:
  - transforms: oxe_no_remapping
  - language_encoders: florence # florence lang_clip

num_workers: ${num_workers}
batch_size: ${batch_size}
pin_memory: ${pin_memory}
drop_last: ${drop_last}

datasets:
  DATA_NAME: ${DATA_NAME}
  DATA_PATH: "gs://gresearch/robotics" # default data path
  load_camera_views: ${load_camera_views}
  dataset_size_limit: ${dataset_size_limit}
  action_proprio_normalization_type: bounds # bounds # normal
  proprio_obs_key: proprio
  interleaved_dataset_cfg:
    shuffle_buffer_size: ${shuffle_buffer_size}
    # change to 500k for training, large shuffle buffers are important, but adjust to your RAM
    # batch_size: None
    balance_weights: True
    traj_transform_kwargs:
      goal_relabeling_strategy: ${goal_relabeling_strategy}
      goal_relabeling_kwargs: 
        goal_relabeling_kwargs:
          min_bound: 20
          max_bound: 50
          frame_diff: 3
      window_size: ${obs_seq_len}
      action_horizon: ${act_seq_len}
      max_action_dim: ${act_dim} # adds padding to actions with less dimension (for joint_mix: [#joints] + [#gripper])
      max_proprio_dim: ${max_proprio_dim} # adds padding to proprio with less dimension (for joint_mix: [#joints] + [#gripper])
      subsample_length: ${subsample_length} # splits trajectories after 100 samples
      skip_unlabeled: ${skip_unlabeled}
    frame_transform_kwargs:
        image_augment_kwargs:
            "primary":
                random_resized_crop:
                  scale: [0.8, 1.0]
                  ratio: [0.9, 1.1]
                random_brightness: [0.1]
                random_contrast: [0.9, 1.1]
                random_saturation: [0.9, 1.1]
                random_hue: [0.05]
                augment_order: [
                    "random_resized_crop",
                    "random_brightness",
                    "random_contrast",
                    "random_saturation",
                    "random_hue",
                ]
            "secondary":
                random_resized_crop:
                  scale: [0.8, 1.0]
                  ratio: [0.9, 1.1]
                random_brightness: [0.1]
                random_contrast: [0.9, 1.1]
                random_saturation: [0.9, 1.1]
                random_hue: [0.05]
                augment_order: [
                    "random_resized_crop",
                    "random_brightness",
                    "random_contrast",
                    "random_saturation",
                    "random_hue",
                ]
            "wrist":
                random_brightness: [0.1]
                random_contrast: [0.9, 1.1]
                random_saturation: [0.9, 1.1]
                random_hue: [0.05]
                augment_order: [
                    "random_brightness",
                    "random_contrast",
                    "random_saturation",
                    "random_hue",
                ]
        resize_size:
            primary: [224, 224]
            secondary: [224, 224]
            wrist: [224, 224] 
        resize_size_future_obs:
            primary: [112, 112]
            secondary: [112, 112]
            wrist: [112, 112]
        num_parallel_calls: 64 # 1024 # 512 # 256
    traj_transform_threads: 12 # 512 # 256 # 128
    traj_read_threads: 12 # 512 # 256 # 128